// ─── BASE "HUNTER" · 50 prospectos (sanitarios / agua / construcción) ─────────
// Fuente: informe "Hunter de cuentas argentinas para una agencia: 50 prospectos con oportunidad digital".
// Se carga en el CRM con el botón "Importar lista Hunter". pitch:
//   rescate = rescatar presencia y convertirla · demanda = generación de demanda + WhatsApp/e-commerce
//   performance = performance / CRM / omnicanal
window.HUNTER_PROSPECTS = [
  { r:1, company:'Estalgrif', industry:'Fabricante de griferías', pitch:'rescate', web:'https://www.estalgrif.com/', email:'info@estalgrif.com', phone:'11-2749-0306',
    why:'Fabricante argentino de griferías con sitio y múltiples canales sociales.',
    gap:'La home indexada conserva texto genérico en inglés de una plantilla de muebles: falla visible de QA, posicionamiento y confianza.',
    pieza:'Mockup de una nueva home + campaña de una línea de grifería + remarketing.' },
  { r:2, company:'Sanitarios Gaona', industry:'Casa de sanitarios', city:'Haedo y Luján', pitch:'demanda', web:'https://sanitariosgaona.com.ar/',
    contactName:'Gustavo Añel', role:'Presidente / Gerente Comercial', linkedin:'https://ar.linkedin.com/in/gustavo-a%C3%B1el-6621601a0',
    alt:'Tomás Añel — Gerente de compras y ventas (LinkedIn: https://ar.linkedin.com/in/tomasa%C3%B1el)',
    why:'Dos sucursales; vende baño, cocina, calefacción, instalaciones, bombas, riego/incendio y revestimientos.',
    gap:'Web funcional pero con huellas muy legacy (incluido “Power by NTSS SAS”) y mucho catálogo con poca capa de generación de demanda.',
    pieza:'Auditoría “cómo generar demanda de obra y refacción sin depender sólo del tráfico que ya busca la marca”.' },
  { r:3, company:'Nesgamet S.A.', industry:'Materiales / sanitarios', pitch:'rescate', web:'https://nesgamet.com.ar/', phone:'+54 9 11 2553-1251', whatsapp:'5491125531251', email:'nesgamet@hotmail.com',
    why:'Unos 80 años de trayectoria; atiende profesionales de la construcción, ferreterías, sanitarios y usuario final.',
    gap:'Presencia online muy modesta comparada con ocho décadas de autoridad offline. Casi el ICP de manual.',
    pieza:'“80 años de autoridad que Google y Meta todavía no están monetizando”: contenido, SEO local y leads profesionales.' },
  { r:4, company:'Hidronorte', industry:'Bombas, calefacción, sanitarios', pitch:'demanda', web:'https://hidronorte.com.ar/', phone:'+54 9 11 2493-3333', whatsapp:'5491124933333',
    why:'20+ años, gran amplitud de categorías y capacidad de e-commerce. Es el benchmark del ICP.',
    gap:'Muchas categorías permiten campañas por problema/intención, pero el activo digital está muy orientado a catálogo/transacción.',
    pieza:'Separar bombas, piscina, calefacción y riego en funnels: Reels técnicos + catálogo + Click-to-WhatsApp + retargeting.' },
  { r:5, company:'Prego Grifería', industry:'Marca de grifería', city:'CABA', pitch:'demanda', web:'https://pregogriferia.com.ar/', phone:'011 5467-1802', email:'info@pregogriferia.com.ar',
    why:'Marca argentina con más de 20 años y distribución mayorista nacional.',
    gap:'Para su alcance comercial, la presencia propia es bastante simple. Mucha oportunidad B2B2C con distribuidores y arquitectos.',
    pieza:'Video de líneas/acabados + campañas “dónde comprar” + generación de demanda para distribuidores.' },
  { r:6, company:'EMB', industry:'Bombas, sanitarios, riego', pitch:'demanda', web:'https://www.bombas-emb.com.ar/', phone:'+54 11 4836-1419 · +54 11 6529-2300', email:'info@bombas-emb.com.ar',
    why:'Más de 30 años en bombas, sanitarios, griferías y riego; trabaja con FV, Rowa, Vulcano, Waterplast y MiPileta.',
    gap:'Extremadamente cercano a nuestro ecosistema. Web más de catálogo/información que de adquisición.',
    pieza:'Caso MiPileta como credencial + campañas por “problema”: presión, riego, piscina, cocina.' },
  { r:7, company:'Banchero Sanitarios', industry:'Casa de sanitarios', pitch:'performance', web:'https://bancherosanitarios.com.ar/', instagram:'@bancherosanitarios',
    contactName:'Juan Ignacio Banchero', role:'Gerente de Operaciones (desde 2025)', linkedin:'https://ar.linkedin.com/in/juanbanchero',
    alt:'También aparecen perfiles de ventas online / e-commerce (Lucas Vanzulli, Nicolás Benvenutto).',
    why:'35+ años, más de 25 marcas, tres sucursales y departamento de obras para constructoras, arquitectos y desarrolladores. Distribuye MiPileta.',
    gap:'Ya tiene web, e-commerce, Instagram y Facebook: no vender “presencia” sino escalamiento, CRM, atribución, obras y performance omnicanal.',
    pieza:'“Cómo medir qué campañas terminan en venta de sucursal u obra” — no community management.' },
  { r:8, company:'Del Sur Sanitarios', industry:'Casa de sanitarios', pitch:'demanda', web:'https://delsursanitarios.com.ar/', phone:'4201-7088 · 4222-0191', whatsapp:'5491170145585',
    why:'Empresa familiar con más de 30 años y dos puntos comerciales.',
    gap:'Activo offline fuerte que puede apalancarse mucho más con contenido, SEO geográfico, Meta y captación para reforma/obra.',
    pieza:'Campaña “renová baño / cocina” + formularios/WhatsApp + retargeting de categorías.' },
  { r:9, company:'CasaRom', industry:'Sanitarios y materiales', city:'Mar del Plata', pitch:'demanda', web:'https://casarom.com.ar/', phone:'+54 9 223 583-8678', whatsapp:'5492235838678', email:'info@casarom.com.ar',
    why:'30 años distribuyendo sanitarios, griferías y materiales; casa central y dos showrooms.',
    gap:'La escala física es muy interesante frente a la sofisticación digital aparente. Tres locales permiten demostrar ROAS geográfico y visitas a showroom.',
    pieza:'Reels desde showroom + campañas en Mar del Plata + formularios de presupuesto de obra.' },
  { r:10, company:'El Águila Sanitarios', industry:'Sanitarios y calefacción', city:'Mar del Plata', pitch:'demanda', web:'https://elaguilasanitarios.com.ar/', phone:'+54 9 223 473-9393 / 600-6716', whatsapp:'5492234739393', email:'info@elaguilasanitarios.com',
    why:'Casa central, otra sucursal y un departamento específico de calefacción.',
    gap:'Buena infraestructura comercial; oportunidad en diferenciación, contenido, automatización y paid local.',
    pieza:'Dos funnels: “baño/cocina” y “calefacción”, con creatividades y audiencias distintas.' },
  { r:11, company:'Sanitarios Arieta', industry:'E-commerce de sanitarios', city:'San Justo', pitch:'demanda', web:'https://www.sanitariosarieta.com.ar/', phone:'(011) 2040-1021 / 7078-0191',
    why:'E-commerce de sanitarios, griferías, bombas y tanques, con propuesta específica para empresas y obras.',
    gap:'El negocio ya dice que quiere obras; falta convertir eso en una máquina digital B2B de leads y nurturing.',
    pieza:'Landing “presupuesto de obra” + lead ads / Google + automatización comercial.' },
  { r:12, company:'Sanitarios Vera', industry:'Casa de sanitarios', city:'CABA', pitch:'rescate', web:'https://www.sanitariosvera.com.ar/', phone:'4857-0220 / 4855-8429', email:'ventas@sanitariosvera.com.ar',
    why:'Opera desde 1992; sanitarios, griferías, caños, tanques y bombas. Av. Corrientes 4978.',
    gap:'Sitio correcto pero muy genérico para más de tres décadas. El diferencial de asesoramiento y autoridad está subexplotado.',
    pieza:'Contenido “cómo elegir…” + performance local + Google Shopping / catálogo.' },
  { r:13, company:'Hidro-San', industry:'Sanitarios y repuestos', city:'Villa Devoto', pitch:'rescate', web:'https://hidrosan.com.ar/', phone:'(011) 4568-6879', whatsapp:'5491149163942', email:'info@hidrosan.com.ar',
    why:'Tienda con sanitarios, griferías, herramientas y repuestos.',
    gap:'Web sobre plantilla Hestia/ThemeIsle con errores de copy como “culsultes”. Quick wins obvios de marca y conversión.',
    pieza:'Mostrar una landing rehecha y un funnel Click-to-WhatsApp.' },
  { r:14, company:'Sanitarios Gino', industry:'Casa de sanitarios', city:'Berazategui y Hudson', pitch:'performance', web:'https://sanitariosgino.com/', phone:'+54 11 3899-3854 · +54 11 3062-0046',
    why:'35+ años, dos sucursales, más de 35 marcas, atención mayorista y minorista.',
    gap:'La web ya está orientada a presupuesto: vender optimización de lead-to-sale, CRM y performance, no diseño básico.',
    pieza:'Auditoría del funnel WhatsApp → presupuesto → venta + retargeting.' },
  { r:15, company:'24 Calefacción', industry:'Calefacción', city:'Avellaneda, Canning, Temperley', pitch:'demanda', web:'https://www.tienda24calefaccion.com/', phone:'011 4264-2287 / 2136-1427',
    why:'Tres puntos comerciales; el sitio identifica al equipo comercial.',
    gap:'Categorías de ticket alto y muy estacionales: escenario ideal para pauta, base de datos y remarketing.',
    pieza:'Campaña otoño/invierno + video “qué equipo necesitás” + captación de presupuestos.' },
  { r:16, company:'Sanitarios Campana SRL', industry:'E-commerce multimarca', city:'Villa del Parque', pitch:'demanda', web:'https://sanitarioscampana.com.ar/', phone:'011 3489-9233', email:'online@sanitarioscampana.com.ar',
    why:'E-commerce multimarca, local físico e Instagram/Facebook enlazados.',
    gap:'No necesita “tener redes”: necesita que catálogo, contenido y pauta trabajen juntos y bajen la dependencia de marketplaces/precio.',
    pieza:'Comparativa de producto + Click-to-WhatsApp + remarketing dinámico.' },
  { r:17, company:'Global Sanitarios', industry:'Sanitarios', city:'CABA', pitch:'rescate', web:'https://www.sanitariosglobal.com.ar/', phone:'011 4864-9656',
    why:'Comercio especializado con tienda online. Ecuador 454, CABA.',
    gap:'Huella WordPress/e-commerce bastante legacy: oportunidad de UX, SEO, conversión y actualización de marca.',
    pieza:'Before/after de home o categoría + campaña de renovación de baño.' },
  { r:18, company:'Casa Fernandes', industry:'Calefacción, bombas, sanitarios', pitch:'demanda', web:'https://casafernandes.com.ar/',
    why:'Vende calefacción, termotanques, bombas, termostatos, griferías y sanitarios. Mix muy parecido a Hidronorte.',
    gap:'Se puede reorganizar la adquisición alrededor de necesidades, no de SKUs.',
    pieza:'Tres conceptos: “me falta presión”, “necesito agua caliente”, “quiero calefaccionar”.' },
  { r:19, company:'Casa Paulino', industry:'Sanitarios', city:'Villa Devoto', pitch:'rescate',
    why:'Comercio con más de 20 años según directorios. Joaquín V. González 3366.',
    gap:'Descubribilidad propia muy baja frente a la antigüedad del negocio. Validar teléfono y dueño antes de contactar.',
    pieza:'Google Business + landing + Meta local + WhatsApp.' },
  { r:20, company:'Sanitarios Hogar', industry:'Sanitarios con e-commerce', city:'Ituzaingó', pitch:'performance', web:'https://www.sanitarioshogar.com.ar/',
    why:'Más de 35 años, showroom, e-commerce y logística propia en CABA/GBA.',
    gap:'Ya tiene buena base digital. El potencial está en testeo creativo, bundles, conversión, retargeting y lifecycle.',
    pieza:'Creatividades de ambiente, financiación y packs de baño completos.' },
  // ── Segunda ola ──
  { r:21, company:'Grupo Suárez', industry:'Sanitarios / griferías', city:'San Miguel de Tucumán', pitch:'rescate',
    why:'Jugador regional del rubro en Tucumán. Juan Larrea 452.', gap:'Poca huella de medios propios frente a su presencia regional. Validar decisor.', pieza:'Presencia + performance regional.' },
  { r:22, company:'Sanitarios Ascensión S.R.L.', industry:'Sanitarios', city:'Morón', pitch:'rescate',
    why:'Comercio relevante con base visible de reseñas locales.', gap:'Su reputación local parece superar su infraestructura digital. Buscar dueño/gerente antes de escribir.', pieza:'Google Business + Meta local + WhatsApp.' },
  { r:23, company:'Sanitarios Sanigas', industry:'Sanitarios', city:'Zona Sur (Banfield)', pitch:'demanda', phone:'011 4244-9157',
    why:'Presencia en Zona Sur y cientos de reseñas en sus sucursales.', gap:'Huella fragmentada entre locales y perfiles; el Facebook de Banfield muestra última publicación de marzo 2026.', pieza:'Consolidar perfiles + captación local por sucursal.' },
  { r:24, company:'IMEPHO', industry:'Proveedor de construcción', city:'Mar del Plata', pitch:'performance', web:'https://imepho.com.ar/', phone:'0223 465-0115 / 4495',
    why:'Planta/sucursal, sanitarios y venta a obras.', gap:'Ideal para ABM B2B: constructoras, arquitectos y desarrollistas.', pieza:'Programa de captación B2B para obras.' },
  { r:25, company:'La Noria Online', industry:'E-commerce', pitch:'performance', web:'https://www.lanoriaonline.com.ar/',
    why:'Sólo baños/sanitarios tenía 188 productos.', gap:'Digitalmente más madura: oportunidad en conversión, feeds, pauta y retargeting. Contacto: equipo de e-commerce/marketing.', pieza:'Auditoría de feeds + remarketing dinámico.' },
  { r:26, company:'Aqualaf', industry:'Marca de grifería', pitch:'demanda', web:'https://aqualaf.com.ar/', email:'contact@aqualaf.com.ar',
    why:'Marca nacional con red extensa de distribuidores.', gap:'Modelo B2B2C: generar demanda de consumidor y derivarla al distribuidor.', pieza:'Campañas “dónde comprar” para la red de distribuidores.' },
  { r:27, company:'Robinet', industry:'Marca de grifería', city:'Olivos', pitch:'demanda', web:'https://www.robinet.com.ar/', phone:'011 4794-1217', email:'robinet@robinet.com.ar',
    why:'Marca argentina de grifería con presencia comercial propia.', gap:'Categoría muy visual pero huella pública discreta.', pieza:'Contenido visual de producto + campañas de marca.' },
  { r:28, company:'Waterplast / Unike Group', industry:'Tanques y gestión de agua', pitch:'demanda',
    contactName:'Vanina Cavalieri', role:'Gerente Comercial', linkedin:'https://ar.linkedin.com/in/vanina-cavalieri',
    why:'Encaje directo en almacenamiento/gestión de agua y canal sanitario.', gap:'Hablar de generación de demanda para el canal de distribución.', pieza:'Demand generation para distribuidores.' },
  { r:29, company:'Motorarg', industry:'Bombas / motores', pitch:'performance', web:'https://www.motorarg.com.ar/', phone:'+54 11 4135-7000 · 0810-666-8672',
    why:'Empresa argentina desde 1957, operación industrial en Buenos Aires y San Luis.', gap:'Mucha autoridad industrial y producto técnico: instaladores, canal y demand generation.', pieza:'Contenido técnico para instaladores + canal.' },
  { r:30, company:'Czerweny', industry:'Motores / electrobombas', pitch:'performance', web:'https://czerweny.ar/', phone:'+54 341 792-1137', instagram:'@czerweny.ar',
    why:'Fabricante argentino con unos 85 años de trayectoria.', gap:'Más interesante para contenido técnico, canal e instaladores que para community management.', pieza:'Contenido técnico + programa de instaladores.' },
  { r:31, company:'Rowa', industry:'Bombas presurizadoras', pitch:'demanda', web:'https://bombasrowa.com/', phone:'+54 11 4717-1405 · 0810-362-ROWA', email:'info@bombasrowa.com',
    why:'Marca especializada en presurización/bombas.', gap:'Problema de consumidor extremadamente marketeable: “tengo baja presión”.', pieza:'Campaña “¿baja presión?” + contenido educativo.' },
  { r:32, company:'Euterma', industry:'Calefacción y climatización', pitch:'demanda', web:'https://www.euterma.com.ar/',
    why:'Calefacción, agua caliente, radiadores y climatización de piscinas.', gap:'Ticket + estacionalidad + necesidad de asesoramiento = buen lead-gen. Contacto corporativo desde su sitio.', pieza:'Lead-gen estacional con asesoramiento.' },
  { r:33, company:'RotorPump', industry:'Bombas', pitch:'performance', web:'https://rotorpump.com/',
    why:'Bombas residenciales/industriales vinculadas a Franklin Electric.', gap:'Education marketing, distribuidores e instaladores. Buscar responsable comercial/canal.', pieza:'Contenido educativo para instaladores.' },
  { r:34, company:'Vulcano S.A.', industry:'Piscinas, bombas, tratamiento de agua', pitch:'performance', web:'https://vulcano-sa.com.ar/',
    why:'Fabrica y comercializa piscinas, bombas, hidromasajes y tratamiento de agua.', gap:'Muy buen fit sectorial aunque digitalmente más desarrollada: pitch de performance/canal, no de “presencia”.', pieza:'Performance + canal.' },
  { r:35, company:'Grifería Peirano', industry:'Marca de grifería', pitch:'performance', web:'https://griferiapeirano.com/', phone:'0810-555-7834 · +54 11 4509-6060',
    why:'Empresa familiar con más de 85 años, ISO 9001 y garantía de cinco años.', gap:'Detalle de QA: una página de soporte llegó a indexar un placeholder tipo info@yourcompany.example.com.', pieza:'Performance/CRM + corrección de detalles de marca.' },
  { r:36, company:'Hidromet', industry:'Fabricante de grifería', city:'San Fernando', pitch:'performance', web:'https://www.hidromet.com.ar/', phone:'+54 11 5263-3444', instagram:'@hidrometgriferias',
    why:'Fabricante argentino con 45 años y garantía de diez años.', gap:'Tiene Instagram y Reels: el pitch debería ser creative/performance/arquitectura.', pieza:'Creatividad + performance + arquitectos.' },
  { r:37, company:'Piazza', industry:'Marca de grifería', city:'Parque Industrial Pilar', pitch:'performance', web:'https://www.piazzagriferia.com/', phone:'(0230) 453-3500',
    why:'Marca histórica, fábrica en Pilar, 51–200 empleados.', gap:'Señales de fragmentación digital: portal legacy todavía indexado junto a la presencia nueva.', pieza:'Unificación de presencia + performance.' },
  { r:38, company:"D'accord Sanitarios", industry:'Sanitarios', pitch:'performance', web:'https://www.daccord.com.ar/', phone:'(54 11) 4753-8129 / 4755-3979', email:'info@daccord.com.ar',
    why:'Fundada en 1979; 51–200 empleados en LinkedIn.', gap:'Presencia bastante activa: cuenta para performance/brand, no un “rescate digital”.', pieza:'Performance + brand.' },
  { r:39, company:'Sanitarios Lamas', industry:'Sanitarios', city:'Olivos', pitch:'performance', web:'https://sanitarioslamas.com.ar/', whatsapp:'5491135711883',
    why:'30+ años, más de 1.500 productos, 35+ marcas, mayorista/minorista y showroom.', gap:'Ya tiene buena base: atacar CRM, profesionales, catálogo y performance.', pieza:'CRM para profesionales + performance de catálogo.' },
  // ── Para validar antes de contactar (red Aqualaf) ──
  ...[
    [40,'Distribuidora COMSA','Banfield','(011) 2071-5502 · Manuel Baliña 1151','Distribuidor confirmado; presencia propia poco visible.'],
    [41,'Distribuidora DISAMAR','Banfield','(011) 4273-5130 · Int. Tavano 1446','Negocio real en canal, medios propios poco visibles.'],
    [42,'Sanitarios Aijon','San Nicolás','Almafuerte 770','Potencial regional; validar escala.'],
    [43,'Sanitarios Ataguile','CABA','(011) 4901-4042 · Acoyte 186','Buena ubicación y sector; poca descubribilidad propia.'],
    [44,'Sanitarios Santucho','CABA','Rivadavia 3254: 011 6081-3200 · Yapeyú 8: 011 4981-4875','Dos puntos: potencial para performance hiperlocal.'],
    [45,'Sanitarios Sione','CABA','(011) 4541-3899 · Washington 3553','Target de SEO/Maps/Meta local; validar tamaño.'],
    [46,'Todo Para Instalar','La Plata','0221 15-356-0207 · Av. 25 Nº 1834','Categoría con buena intención de búsqueda; baja huella propia.'],
    [47,'Sanitarios Torino','La Tablada','(011) 4652-2861 · Av. San Martín 5255','Prospección local secundaria.'],
    [48,'Sanitarios Viamonte','Lanús Oeste','(011) 4247-9208 · Viamonte 1069','Fit vertical alto, tamaño por confirmar.'],
    [49,'Sanitarios Yrigoyen','Florencio Varela','(011) 4255-8398 · Av. Hipólito Yrigoyen 1670','Buen candidato para Google/Meta/WhatsApp local si el tamaño da.'],
    [50,'Zárate Materiales','Córdoba','Monseñor P. Cabrera 5030 y Recta Martinolli 7988','Presencia física/distribución interesante; confirmar decisor y escala.'],
  ].map(([r,company,city,phone,gap])=>({ r, company, city, phone, industry:'Sanitarios (red Aqualaf)', pitch:'rescate', validate:true,
    why:'Aparece en la red oficial de distribución de Aqualaf.', gap, pieza:'Google Business + Meta local + WhatsApp (validar tamaño y dueño antes).' })),
];
